dist: trusty

language: node_js

# override travis-core configuration, see
# http://witkowskibartosz.com/blog/github-pages-and-travis-auto-deployment.html
branches:
  only:
    - /gh-pages.*/
    - /.*/

node_js:
  - '7'

addons:
  chrome: stable

cache:
  directories:
    - node_modules

before_script:
  # install aws cli to upload artifacts
  - sudo pip install awscli

  # prepare e2e test environment
  - npm run test:setup -s
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

script:
  - npm run generate
  - npm run serve &>/dev/null &
  - sleep 5 # give server some time to start
  - npm test

after_script:
  - aws s3 cp tests_output s3://${ARTIFACTS_BUCKET}/gh-pages-source/${TRAVIS_BUILD_NUMBER} --recursive

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: public
  github_token: $GITHUB_TOKEN
  on:
    branch: gh-pages-source
