language: node_js
node_js:
  - '7'

before_script:
  - npm install -q

script:
  - npm run lint -s
  - npm run lint:report -s
  - npm run test -s
  - npm run compile

after_success:
  cat target/coverage/lcov.info | ./node_modules/.bin/codacy-coverage
